3.0 FEATURE SET 11: TALEA RHYTHM-MAKER, CROSS-SEGMENT TRILL SPANNERS.
RHYTHM-MAKERS:

    * Added abjad.Talea.preamble;
        use for introductory counts prior to repetition of talea counts

    * Added rhythmmakertools.Talea.advance():

        >>> talea = abjad.rhythmmakertools.Talea(
        ...     counts=[2, 1, 3, 2, 4, 1, 1],
        ...     denominator=16,
        ...     preamble=[1, 1, 1, 1],
        ...     )

        >>> abjad.f(talea.advance(0))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[1, 1, 1, 1],
            )

        >>> abjad.f(talea.advance(1))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[1, 1, 1],
            )

        >>> abjad.f(talea.advance(2))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[1, 1],
            )

        >>> abjad.f(talea.advance(3))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[1],
            )

        >>> abjad.f(talea.advance(4))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            )

        >>> abjad.f(talea.advance(5))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[1, 1, 3, 2, 4, 1, 1],
            )

        >>> abjad.f(talea.advance(6))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[1, 3, 2, 4, 1, 1],
            )

        >>> abjad.f(talea.advance(7))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[3, 2, 4, 1, 1],
            )

        >>> abjad.f(talea.advance(8))
        abjad.rhythmmakertools.Talea(
            counts=[2, 1, 3, 2, 4, 1, 1],
            denominator=16,
            preamble=[2, 2, 4, 1, 1],
            )

    * Taught TaleaRhythmMaker about previous weight consumed;
        TaleaRhythmMaker publishes postcall state['talea_weight_consumed']

    * Added TaleaRhythmMaker.__call__(..., state=None) keyword;
        changed rhythm-maker rotation=None keyword to state=None dictionary;
        pass {'rotation': value} to recoup previous interface

    * Removed long-deprecated private rhythm-maker _helper_functions

TRILL SPANNERS:

    Activated cross-segment trill spanners:

    Trill spanners can be broken tagged for use across segment boundaries:

    >>> segment_1 = abjad.Voice("c'4 d' e' f'", name='MainVoice')
    >>> abjad.attach(abjad.TrillSpanner(), segment_1[:], right_broken=True)
    >>> abjad.f(segment_1, strict=True)
    \context Voice = "MainVoice" {
        c'4
        \startTrillSpan
        d'4
        e'4
        f'4
        \stopTrillSpan %! RIGHT_BROKEN_TRILL
    }

    >>> segment_2 = abjad.Voice("g'4 f'2 r4", name='MainVoice')
    >>> abjad.attach(abjad.TrillSpanner(), segment_2[:], left_broken=True)
    >>> abjad.f(segment_2, strict=True)
    \context Voice = "MainVoice" {
        g'4
        \startTrillSpan %! LEFT_BROKEN_TRILL
        f'2
        r4
        \stopTrillSpan
    }

    >>> container = abjad.Container([segment_1, segment_2])
    >>> abjad.f(container, strict=True)
    {
        \context Voice = "MainVoice" {
            c'4
            \startTrillSpan
            d'4
            e'4
            f'4
            \stopTrillSpan %! RIGHT_BROKEN_TRILL
        }
        \context Voice = "MainVoice" {
            g'4
            \startTrillSpan %! LEFT_BROKEN_TRILL
            f'2
            r4
            \stopTrillSpan
        }
    }

    >>> text = format(container, 'lilypond:strict')
    >>> text = abjad.LilyPondFormatManager.left_shift_tags(text)
    >>> tags_ = [
    ...     abjad.tags.LEFT_BROKEN_TRILL, abjad.tags.RIGHT_BROKEN_TRILL,
    ...     ]
    >>> match = lambda tags: set(tags) & set(tags_)
    >>> text, count = abjad.deactivate(text, match)
    >>> print(text)
    {
        \context Voice = "MainVoice" {
            c'4
            \startTrillSpan
            d'4
            e'4
            f'4
        %%% \stopTrillSpan %! RIGHT_BROKEN_TRILL
        }
        \context Voice = "MainVoice" {
            g'4
        %%% \startTrillSpan %! LEFT_BROKEN_TRILL
            f'2
            r4
            \stopTrillSpan
        }
    }

    FIXED:

    * Fixed ancient bug:
      OLD: pitched trill spanners hid markup attached to same leaf;
      NEW: pitched trill spanners do not hide markup attached to same leaf

INDICATORS:

    * Added abjad.MarginMarkup

    * Added abjad.RehearsalMark.from_string()

Developer updates:

    New modeling affordance for developers:

        NEW: simultaneous contexted indicators are now allowed if only one is
        active (and all others are inactive).

        REMINDER: two contexted indicators can not be attached at the same
        offset if both indicators are active:

        >>> staff = abjad.Staff("c'4 d' e' f'")
        >>> abjad.attach(abjad.Clef('treble'), staff[0])
        >>> abjad.attach(abjad.Clef('alto'), staff[0])
        Traceback (most recent call last):
            ...
        Exception: Can not attach ...

        Example:

        >>> staff = abjad.Staff("c'4 d' e' f'")
        >>> abjad.attach(abjad.Clef('treble'), staff[0])
        >>> abjad.attach(
        ...     abjad.Clef('alto'),
        ...     staff[0],
        ...     deactivate=True,
        ...     tag='+PARTS_1',
        ...     )
        >>> abjad.attach(
        ...     abjad.Clef('tenor'),
        ...     staff[0],
        ...     deactivate=True,
        ...     tag='+PARTS_2',
        ...     )

        >>> abjad.f(staff, strict=True)
        \new Staff {
            \clef "treble"
        %@% \clef "alto" %! +PARTS_1
        %@% \clef "tenor" %! +PARTS_2
            c'4
            d'4
            e'4
            f'4
        }

        Active indicator is always effective when competing inactive indicators
        are present:

        >>> for note in staff:
        ...     clef = abjad.inspect(staff[0]).get_effective(abjad.Clef)
        ...     note, clef
        ...
        (Note("c'4"), Clef('treble'))
        (Note("d'4"), Clef('treble'))
        (Note("e'4"), Clef('treble'))
        (Note("f'4"), Clef('treble'))

        But a lone inactivate indicator is effective when no active indicator
        is present:

        >>> staff = abjad.Staff("c'4 d' e' f'")
        >>> abjad.attach(
        ...     abjad.Clef('alto'),
        ...     staff[0],
        ...     deactivate=True,
        ...     tag='+PARTS',
        ...     )

        >>> abjad.f(staff, strict=True)
        \new Staff {
        %@% \clef "alto" %! +PARTS
            c'4
            d'4
            e'4
            f'4
        }

        >>> for note in staff:
        ...     clef = abjad.inspect(staff[0]).get_effective(abjad.Clef)
        ...     note, clef
        ...
        (Note("c'4"), Clef('alto'))
        (Note("d'4"), Clef('alto'))
        (Note("e'4"), Clef('alto'))
        (Note("f'4"), Clef('alto'))

        This affordance is unlikely to be used often.

        Affordance is provided for differing editions of scores and parts,
        where, for example, score may contain margin markup that says "Violins
        1-10" but violin 1 part should suppress that margin markup and instead
        activate part-appropriate margin markup that says "Violin 1".

    NEW: Added abjad.detach(..., by_id=False) keyword.

        Consider the three document-specifier markups below:

        >>> markup_1 = abjad.Markup('tutti', direction=abjad.Up)
        >>> markup_2 = abjad.Markup('with the others', direction=abjad.Up)
        >>> markup_3 = abjad.Markup('with the others', direction=abjad.Up)

        But document-tagging like this makes sense for score and two diferent
        parts:

        >>> staff = abjad.Staff("c'4 d' e' f'")
        >>> abjad.attach(markup_1, staff[0], tag='+SCORE')
        >>> abjad.attach(
        ...     markup_2,
        ...     staff[0],
        ...     deactivate=True,
        ...     tag='+PARTS_VIOLIN_1',
        ...     )
        >>> abjad.attach(
        ...     markup_3,
        ...     staff[0],
        ...     deactivate=True,
        ...     tag='+PARTS_VIOLIN_2',
        ...     )

        >>> abjad.f(staff, strict=50)
        \new Staff {
            c'4
            ^ \markup {
                \column
                    {
                        \line                             %! +SCORE
                            {                             %! +SCORE
                                tutti                     %! +SCORE
                            }                             %! +SCORE
                    %@% \line                             %! +PARTS_VIOLIN_1
                    %@%     {                             %! +PARTS_VIOLIN_1
                    %@%         "with the others"         %! +PARTS_VIOLIN_1
                    %@%     }                             %! +PARTS_VIOLIN_1
                    %@% \line                             %! +PARTS_VIOLIN_2
                    %@%     {                             %! +PARTS_VIOLIN_2
                    %@%         "with the others"         %! +PARTS_VIOLIN_2
                    %@%     }                             %! +PARTS_VIOLIN_2
                    }
                }
            d'4
            e'4
            f'4
        }

        The question is then how to detach just one of the two markups that
        compare equal to each other?
        Passing in one of the markup objects directory doesn't work. This is
        because detach tests for equality to input argument.

        Instead set ``by_id`` to true. Detach then checks the exact id of
        its input argument (rather than just testing for equality) and detaches
        exactly the one markup we pass in:

        >>> abjad.detach(markup_2, staff[0], by_id=True)
        (Markup(contents=['with the others'], direction=Up),)

        >>> abjad.f(staff, strict=50)
        \new Staff {
            c'4
            ^ \markup {
                \column
                    {
                        \line                             %! +SCORE
                            {                             %! +SCORE
                                tutti                     %! +SCORE
                            }                             %! +SCORE
                    %@% \line                             %! +PARTS_VIOLIN_2
                    %@%     {                             %! +PARTS_VIOLIN_2
                    %@%         "with the others"         %! +PARTS_VIOLIN_2
                    %@%     }                             %! +PARTS_VIOLIN_2
                    }
                }
            d'4
            e'4
            f'4
        }

    Additionally:

        * Started adding typehints

        * Taught ajk to ignore .my_cache directories

    SEGMENTS:

        * Added abjad.Job to segmenttools

        * Added abjad.Momento.document property