Extended all containers to raise new GraceContainerError at insert-time in the case that somebody tries to insert a grace container directly into a container.
(This behavior was previously allows. Which is bad. Because grace containers should 
always be attached to leaf.)

Example:

    staff = Staff("c' d' e'")
    grace_container = gracetools.GraceContainer("f'16 g'")
    staff.append(grace_container)
    ...
        raise GraceContainerError('must attach grace container to note or chord.')
    abjad.tools.exceptiontools.GraceContainerError.GraceContainerError: must attach grace container to note or chord.

This closes Google #101.