Note on using pychecker:
A known pychecker bug is defined here ...

    https://bugzilla.redhat.com/show_bug.cgi?id=713591

... and explains that "pychecker fails on list slice assignment".

This causes pychecker to raise a NotImplementedError when running against parts
of the Abjad codebase:

Example:

[system path]/abjad/trunk/abjad/tools/containertools/Container/Container.py:479: INTERNAL ERROR -- STOPPED PROCESSING FUNCTION --
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pychecker/warn.py", line 242, in _checkFunction
        _checkCode(code, codeSource)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pychecker/warn.py", line 155, in _checkCode
        raise NotImplementedError('No DISPATCH member for op %r' % op)
    NotImplementedError: No DISPATCH member for op 43


Conclusion: a problem because pychecker will error before checking all of certain files in the codebase.
But pychecker should still be used everywhere else.