Fixed a bug in import_functions_in_package_to_namespace(package, namespace). The function was trying to load the test files in the test directory. This is no longer the case.
Note that the tools/imports package works in 'online' mode via the abj script, but does not work when a package that uses it is imported from a script file. For example, 

abjad> from abjad.tools import mathtools 

works just fine, but calling the import inside a script throws and import error
ImportError: No module named /home/vadan/projects/abjad/trunk/abjad/tools/imports/get_topmost_module

why?