Added Meter.get_durations_at_depth().
Examples:

    >>> meter = metertools.Meter((7, 4))
    >>> meter.get_durations_at_depth(0)
    [Duration(7, 4)]

    >>> meter.get_durations_at_depth(1)
    [Duration(3, 4), Duration(1, 2), Duration(1, 2)]

    >>> meter.get_durations_at_depth(2)
    [Duration(1, 4), Duration(1, 4), Duration(1, 4), Duration(1, 4), Duration(1, 4), Duration(1, 4), Duration(1, 4)]

Depths greater than 2 raise an exception because
Meter.depthwise_offset_inventory is runs only to depth 2:

    >>> meter.get_durations_at_depth(3)
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/metertools/Meter.py", line 1051, in get_durations_at_depth
        offsets = offset_inventory[depth]
    IndexError: tuple index out of range

Method provides a semantic interface to meter duration, beat-group durations
and beat durations (in that order).