Extended Tempo to handle float-valued input transparently. NEW.
NOTE. LilyPond errors on float-valued tempi!

    \new Staff{
        \tempo 4=90.1
        c'4
        }

    GNU LilyPond 2.19.17
    Processing `test.ly'
    Parsing...
    test.ly:6:14: error: syntax error, unexpected REAL
        \tempo 4=
                90.1
    test.ly:5:1: error: errors found, ignoring music expression

    \new Staff{
    fatal error: failed files: "test.ly"

EXPLANATION. The Abjad code committed here works around this LilyPond
limitation.

OLD. Output looked simple but caused LilyPond to fail:

    >>> score = Score([])
    >>> staff = Staff("c'8 d'8 e'8 f'8")
    >>> score.append(staff)
    >>> tempo = Tempo(Duration(1, 4), 90.1)
    >>> attach(tempo, staff[0])

    >>> f(score)
    \new Score <<
        \new Staff {
            \tempo 4=90.1
            c'8
            d'8
            e'8
            f'8
        }
    >>

NEW. Output does exactly what we want:

    >>> score = Score([])
    >>> staff = Staff("c'8 d'8 e'8 f'8")
    >>> score.append(staff)
    >>> tempo = Tempo(Duration(1, 4), 90.1)
    >>> attach(tempo, staff[0])

    >>> f(score)
    \new Score <<
        \new Staff {
            \tempo \markup {
                \scale
                    #'(0.75 . 0.75)
                    \score
                        {
                            \new Score \with {
                                \override SpacingSpanner #'spacing-increment = #0.5
                                proportionalNotationDuration = ##f
                            } <<
                                \new RhythmicStaff \with {
                                    \remove Time_signature_engraver
                                    \remove Staff_symbol_engraver
                                    \override Stem #'direction = #up
                                    \override Stem #'length = #5
                                    \override TupletBracket #'bracket-visibility = ##t
                                    \override TupletBracket #'direction = #up
                                    \override TupletBracket #'padding = #1.25
                                    \override TupletBracket #'shorten-pair = #'(-1 . -1.5)
                                    \override TupletNumber #'text = #tuplet-number::calc-fraction-text
                                    tupletFullLength = ##t
                                } {
                                    c'4
                                }
                            >>
                            \layout {
                                indent = #0
                                ragged-right = ##t
                            }
                        }
                =
                \general-align
                    #Y
                    #-0.5
                    90.1
                }
            c'8
            d'8
            e'8
            f'8
        }
    >>

NEW. Should be included in the 2.16 release notes.