Harmonized StemTremolo slots implementation. Note included.
NOTE: slotted class attributes break copy.copy() and copy.deepcopy():

Consider this class definition:

    class A(object):

        __slots__ = (
            '_format_slot',
            )

        _format_slot = 'right'

        def __init__(self):
            pass

Copy breaks here:

    >>> a = A()
    >>> a
    <__main__.A object at 0x1004a1a98>
    >>> copy.copy(a)
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 96, in copy
        return _reconstruct(x, rv, 0)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 346, in _reconstruct
        setattr(y, key, value)
    AttributeError: 'A' object attribute '_format_slot' is read-only

The fix is uneasy though perhaps surprising: include *NO* class variables in
slots: just define them on the class:

    class A(object):

        __slots__ = (
            '_foo',
            )

        _format_slot = 'right'

        def __init__(self):
            pass

Now copy works:

    >>> a = A()
    >>> copy.copy(a)
    <__main__.A object at 0x1004a1a28>

This commit changes StemTremolo in exactly the way shown here.