Container addition now raises exception when not possible.
Example 1. Here addition works because the voices have the same name:

>>> left = Voice("c'8 d'8")
>>> left.name = 'voice 1'

>>> right = Voice("e'8 f'8")
>>> right.name = 'voice 1'

>>> left + right
Voice-"voice 1"{4}
>>> f(_)
\context Voice = "voice 1" {
    c'8
    d'8
    e'8
    f'8
}


Example 2. Here addition doesn't work because the voices are named differently:

    >>> left = Voice("c'8 d'8")
    >>> left.name = 'voice 1'

    >>> right = Voice("e'8 f'8")
    >>> right.name = 'FOO'

    >>> left + right
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/trevorbaca/Documents/abjad/trunk/abjad/tools/containertools/Container/Container.py", line 55, in __add__
        raise Exception('can not add.')
    Exception: can not add.

Previously addition returned none.

This should be noted in the change log for the next release.