Added ImageRenderSpecifier workaround to StorageFormatManager.
For several weeks "ajv api -M" had been giving a (non-execution-halting)
traceback on my machine:

    <snip>
    PRESERVED: api/tools/topleveltools/set_.rst
    PRESERVED: api/tools/topleveltools/show.rst
    Returning to /Users/trevorbaca/Documents/abjad/abjad.
    ()
    sphinx-build -b html -d build/doctrees   source build/html
    Running Sphinx v1.2.3
    loading pickled environment... done
    building [html]: targets for 0 source files that are out of date
    updating environment: 0 added, 1 changed, 0 removed
    reading sources... [100%] api/tools/scoretools/Note
        [abjad-book] interpreting: 7 / 7
    installing lightbox files... [100%] lightbox2/js/lightbox.js

    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... done
    preparing documents... done
    Traceback (most recent call last):
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 796, in visit_abjad_output_block_html
        SphinxDocumentHandler.render_png_image(self, node)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 701, in render_png_image
        node, image_render_specifier)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 575, in get_file_base_name
        sha1sum.update(format(image_render_specifier, 'storage').encode('utf-8'))
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abctools/AbjadObject.py", line 44, in __format__
        return systemtools.StorageFormatManager.get_storage_format(self)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/StorageFormatManager.py", line 490, in get_storage_format
        as_storage_format=True,
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/StorageFormatManager.py", line 195, in get_format_pieces
        value = getattr(specification.instance, name)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/ImageRenderSpecifier.py", line 71, in no_resize
        return self._no_resize
    AttributeError: _no_resize
    Traceback (most recent call last):
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 796, in visit_abjad_output_block_html
        SphinxDocumentHandler.render_png_image(self, node)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 701, in render_png_image
        node, image_render_specifier)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 575, in get_file_base_name
        sha1sum.update(format(image_render_specifier, 'storage').encode('utf-8'))
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abctools/AbjadObject.py", line 44, in __format__
        return systemtools.StorageFormatManager.get_storage_format(self)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/StorageFormatManager.py", line 490, in get_storage_format
        as_storage_format=True,
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/StorageFormatManager.py", line 195, in get_format_pieces
        value = getattr(specification.instance, name)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/ImageRenderSpecifier.py", line 71, in no_resize
        return self._no_resize
    AttributeError: _no_resize
    Traceback (most recent call last):
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 796, in visit_abjad_output_block_html
        SphinxDocumentHandler.render_png_image(self, node)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 701, in render_png_image
        node, image_render_specifier)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/SphinxDocumentHandler.py", line 575, in get_file_base_name
        sha1sum.update(format(image_render_specifier, 'storage').encode('utf-8'))
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abctools/AbjadObject.py", line 44, in __format__
        return systemtools.StorageFormatManager.get_storage_format(self)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/StorageFormatManager.py", line 490, in get_storage_format
        as_storage_format=True,
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/StorageFormatManager.py", line 195, in get_format_pieces
        value = getattr(specification.instance, name)
    File "/Users/trevorbaca/Documents/abjad/abjad/tools/abjadbooktools/ImageRenderSpecifier.py", line 71, in no_resize
        return self._no_resize
    AttributeError: _no_resize

    writing additional files... search
    copying images... [100%] gallery/oberholtzer-ersilia-page9.png
    copying downloadable files... [100%] /Users/trevorbaca/Documents/abjad/abjad/docs/source/_stylesheets/default.ly
    copying static files... done
    copying extra files... done
    dumping search index... done
    dumping object inventory... done
    build succeeded.
    rendering gallery thumbnails...[100%] gallery/oberholtzer-ersilia-page9.png

    Build finished. The HTML pages are in build/html.

The complaint given in the traceback means that StorageFormatManager was unable
to find a value for the ImageRenderSpecifier.no_resize property. Which is hard to
explain. Because ImageRenderSpecifier.__init__() always sets a value for the
_no_resize property.

The solution committed here in StorageFormatManager is a workaround:

        for name in specification.keyword_argument_names:
            # TODO: temporary hack while debugging:
            if (name == 'no_resize' and
                specification.instance.__class__.__name__ ==
                'ImageRenderSpecifier'):
                value = None
            else:
                value = getattr(specification.instance, name)

The change causes "ajv api -M" again to run correctly on my machine, without
giving the traceback shown above. Perhaps a more legitimate fix will be
necessary in future. Or perhaps the fix here will suffice indefinitely.