NoteHead is no longer a _GrobHandler; NoteHead now inherits from object instead.
New LilyPondTweakReservoir class to support chord note head tweaks.

NoteHead now aggregates a LilyPondTweakReservoir to tweak chord note heads.

Example:

   abjad> chord = Chord([0, 2, 4], (1, 4))
   abjad> chord.note_heads[1].tweak.color = 'blue'
   abjad> f(chord)
   <
      c'
      \tweak #'color #blue
      d'
      e'
   >4


Python slots introduced in this commit.

NoteHead now implements slots.

NoteHead no longer sets attributes dynamically.

Example:

   abjad> chord.note_heads[1].tweak.color = 'blue'
   abjad> chord.note_heads[1]
   NoteHead(d')
   abjad> chord.note_heads[1].foo = 'bar'
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
   AttributeError: 'NoteHead' object has no attribute 'foo'
   
Removed NoteHeadInterface.

Pickle and slots do not play together.

Removed:

   iotools.dump_pickle( )
   iotools.load_pickle( )

Use skeletonization instead.

New docs/devel/slots chapter on using slots.

API pages added for SchemePair and SchemeVectorConstant.